## Aula de revisão + GITHUB



## Fluxos Sequeciais


Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o imposto de renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê: salário bruto. quanto pagou ao INSS. quanto pagou ao sindicato. o salário liquido. calcule os descontos e o salário líquido, conforme a tabela a baixo:

- Salário Bruto
- IR (11%)
- INSS(8%)
- SINDICATO (5%)

In [4]:
# Solução

# Pedir ao usuario o seu valor por hora

valor_hora = float(input("Digite o seu valor por hora: "))

# Pedir ao usuario o numero de horas trabalhadas no mês

horas_trabalhadas = float(input("Digite o numero de horas trabalhadas no mês: "))

# Multiplicar os dois valores anteriores e guardo numa variavel

salario_bruto = valor_hora * horas_trabalhadas

# Para saber o que pagar de IR, multiplico o salario bruto vezes 11% e guardo numa variavel

valor_ir = salario_bruto * 0.11

# Para saber o que pagar de INSS, multiplico o salario bruto vezes 8% guardo numa variavel

valor_inss = salario_bruto * 0.08

# Para saber o que pagar de SINDICATO, multiplico o salario bruto vezes 5% guardo numa variavel

valor_sindicato = salario_bruto * 0.05

# Imprimo a tabela conforme solicitado

print(f"- salário bruto: R${salario_bruto:.2f}")
print(f"- IR (11%): R${valor_ir:.2f}")
print(f"- INSS (8%): R${valor_inss:.2f}")
print(f"- Sindicato (5%): R${valor_sindicato:.2f}")
print(f"= Salário Liquido: R${salario_bruto - valor_ir - valor_inss - valor_sindicato:.2f}")


- salário bruto: R$2640.00
- IR (11%): R$290.40
- INSS (8%): R$211.20
- Sindicato (5%): R$132.00
= Salário Liquido: R$2006.40


## Fluxos Condicionais

Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:

"Telefonou para vitima?" "Esteve no local do crime ?" "Mora perto da vitima?" "Devia para a vitima?" "Já trabalhou com a vitima?"

O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".

In [20]:
# Solução

# Cria uma lista com todas as perguntas
perguntas = ["Telefonou para vitima?", "Esteve no local do crime?", "Mora perto da vitima?", "Devia para vitima?", "Ja trabalhou com vitima?"]

# Cria uma variável para armazenar as respostas

respostas = 0
# Orientar para que ele responda 0 (n) ou 1 (s)

print("Digite 0 para não e 1 para sim")

# Perguntar ao usuario seguindo a lista

for pergunta in range(len(perguntas)):

# A cada resposta, some a variável 0 (não) ou 1 (sim)

    respostas += int(input("pergunta"))


# Se a quantidade de resposta positivas for igual a 2, imprimir "suspeito"

if (respostas == 2):
    print("suspeito")

# Se a quantidade de resposta positivas for entre 3 e 4, imprimr "cumplice"

elif(respostas == 3 or 4):
    print("cumplice")

# Se a quantidade de resposta positivas for igual a 5, imprimir "assassino"

elif(respostas == 5):
    print("assasino")

# caso contrario, imprimir "inocente"

else:
    print("inocente")

Digite 0 para não e 1 para sim
suspeito


## Fluxos de Repetição

Crie um programa em Python que solicita ao usuario uma senha numérica de 4 digitos. O programa deve repetir essa solicitação até que o usuário informe a senha correta(1234)

In [1]:
# Solução

# Crie um programa em python que solicita ao usuario uma senha de 4 digitos

senha_digitada = int(input("Digite uma senha de 4 digitos: "))

# O programa deve repetir essa solicitação até que o usuario informe a senha correta 123

senha_correta = 1234

while senha_digitada != senha_correta:
    print("senha incorreta, tente novamente! ")
    senha_digitada = input("Digite a senha: ")

print("senha correta")
 

senha correta


# Uso de funções

In [ ]:
def saudacao_by_periodo(horario):
    
    if horario == "M" or "m": # SE 
        print("Bom dia! ")
    elif horario == "V" or "v": # ELSE + IF ---> DEFINE OUTRA CONDIÇÃO CASO A PRIMEIRA SEJA FALSA
        print("Boa tarde! ")
    elif horario == "N" or "n":
        print("Boa noite! ")
    else: # DEFINA UMA MENSAGEM SE TODAS AS CONDIÇÕES ANTERIORES FOREM FALSAS
        return "Valor inválido! "

horario = input("Digite o turno (M-matutino ou V-vespertino ou N-noturno): ")

turnos = ("M", "m", "V", "v", "N", "n")

while horario in turnos: # WHILE --> ENQUANTO A CONDIÇÃO FOR VERDADEIRA
    print(saudacao_by_periodo(horario))
    horario = input("Digite o turno (M-matutino ou V-vespertino ou N-noturno)")

Bom dia! 
None
Bom dia! 
None


## NUMPY: Exemplo

"Resenha de filme" é um site de resenhas de filmes onde quatro bons amiggos e criticos de filmes: gabriel, kleber, leandro e rodrigo assistem a filmes e dão a eles notas em uma escala de 0 a 100

In [ ]:
import numpy as np

[2.   0.75 2.   1.   0.5 ]


Quando toda turma classifica um filme, podemos armazenar suas classificações em um array NumPy movie_ratings:

In [8]:
movie_ratings = np.array([63.0, 54.0, 70.0, 50.0])
movie_ratings.dtype

random_ratings = np.random.rand(4,2)
random_ratings

array([[0.58019398, 0.40254031],
       [0.5708339 , 0.91162446],
       [0.51210616, 0.40730905],
       [0.23341728, 0.9870342 ]])

Mas eles assistem a mais de um filme, então temos que criar uma matriz bidimensional onde cada linha contém suas classificações para um filme específico.

In [18]:
movie_ratings = np.array([[63.0, 54.0, 70.0, 50.0],
                         [94.0, 85.0, 89.0, 95.0],
                         [64.0, 90.0, 73.0, 85.0]])
movie_ratings

array([[63., 54., 70., 50.],
       [94., 85., 89., 95.],
       [64., 90., 73., 85.]])

Alguns fãs preferem que os filmes sejam classificados em uma escala de cinco estrelas, então podemos usar o Numpy para dividir facilmente cada elemento por 20.

In [19]:
movie_ratings_stars = movie_ratings / 20
movie_ratings_stars

array([[3.15, 2.7 , 3.5 , 2.5 ],
       [4.7 , 4.25, 4.45, 4.75],
       [3.2 , 4.5 , 3.65, 4.25]])

Agora, digamos que as classificações estejam sempre na mesma ordem (Luísa, Maria, Tony, Kaio). Se quiséssemos criar uma matriz que tivesse apenas as classificações de Tony, poderíamos selecioná-las em nossa matriz movie_rastings.

In [26]:
tony_ratings = movie_ratings[:, 2]
tony_ratings

array([70., 89., 73.])

Agora, digamos que descobrimos que temos gostos muito parecidos com os de Maria, então queremos ver apenas filmes aos quais ele dá uma boa classificação. Podemos usar a lógica para selecionar esses filmes.

Vamos selecionar todas as classificações de Maria que são acima de 80:

In [28]:
maria_ratings = movie_ratings[:, 1]
maria_ratings[maria_ratings> 80]

array([85., 90.])

## Numpy: Exercicio

Farinha - 2 xícaras açúcar - 0,75 xícaras ovos - 2 ovos leite - 1 xícara manteiga - 0,5 xícaras 

Crie um array Numpy qeu represente esses dodos. Cada elemento deve ser um número (por exemplo, 2 para "2 xícaras"). Salve esse array como cupcakes.

In [29]:
# Solução
cupcakes = np.array([2, 0.75, 2, 1, 0.5])
print(cupcakes)

[2.   0.75 2.   1.   0.5 ]


A assistente de Joana compilou todas as suas receitas em um arquivo csv (comma-separated) chamado recipes.csv. Carregue esse arquivo em uma variável chamada recipes. Cada linha representa uma receita diferente. Cada coluna representa um ingrediente diferente.

In [50]:
# Solução
recipes = np.genfromtxt("recipes.csv", delimiter=",")
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

A 3 coluna representa o número de ovos que cada receita necessita

Selecione todos os elementos da 3 coluna e salve-os na variável eggs.

In [ ]:
# Solução

eggs = cupcakes[:2]
eggs

array([2.  , 0.75])

 Quais receitas exigem exatamente 1 ovo? Use uma declaração lógica para obter True ou False para cada valor de eggs.

In [33]:
# Solução

one_eggs = cupcakes[cupcakes == 1]
one_eggs

array([1.])

Joana fará 2 fornadas de cupcakes (1 fileira) a 1 fornadade biscoitos (3 fileira)

Você já tem uma variável para cupcakes. Crie uma variável cookies com os dados da 3 linha

In [51]:
# Solução

cookies = np.array(recipes[2]) # COPIA A LINHA 3 DO ARRAY RECIPES
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

Obtenha um número de ingredientes para uma porção dupla de cupcakes usando mulpiplicação em cupcakes.

Salve sua nova variavel em double_batch

In [34]:
# Solução
double_batch = cupcakes * 2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

Crie uma nova variável chamada grocery_list adicionando cookies e double_batch.

In [36]:
# Solução

#grocery_list = cookies + double_batch
grocery_list = np.array([cupcakes, double_batch])
grocery_list

array([[2.  , 0.75, 2.  , 1.  , 0.5 ],
       [4.  , 1.5 , 4.  , 2.  , 1.  ]])

## PANDAS: UMA BREVE INTRODUÇÃO

O pandas pode nos fornecer respostas sobre os dados, como por exemplo:

Existe uma correlação entre duas ou mais colunas? Qual é o valor? Qual o valor máximo? Qual o valor mínimo? O pandas também é capaz de excluir linhas que são irrelevantes ou que contêm valores incorretos, como valores vazios ou NULL, deixando os dados limpos.

Relacionando inicialmente as funções do Numpy com o pandas, poderíamos gerar uma série com os dados da porção dupla de cupcakes:

In [37]:
import pandas as pd

In [ ]:
double_batch_series = pd.Series(double_batch) # PARA INCLUIR INDICES PAR ACADA ELEMENTO
double_batch_series

0    4.0
1    1.5
2    4.0
3    2.0
4    1.0
dtype: float64

Podemos gerar um DataFrame a partir de várias series:

In [52]:
df = pd.DataFrame(recipes)
print(df)

      0      1    2    3      4
0  2.00  0.750  2.0  1.0  0.500
1  1.00  0.125  1.0  1.0  0.125
2  2.75  1.500  1.0  0.0  1.000
3  4.00  0.500  2.0  2.0  0.500


Por exemplo, se precisássemos listar as nossas compras do supermercado, teríamos algo semelhante a isso:

In [53]:
df = pd.DataFrame(recipes, columns=['Flour', 'Milk', 'Sugar', 'Butter', 'Eggs'])


In [54]:
df2 = pd.read_csv('recipes.csv', delimiter=',' , names=['Flour', 'Milk', 'Sugar', 'Butter', 'Eggs'])
print(df2)

   Flour   Milk  Sugar  Butter   Eggs
0   2.00  0.750      2       1  0.500
1   1.00  0.125      1       1  0.125
2   2.75  1.500      1       0  1.000
3   4.00  0.500      2       2  0.500


Exercicios escolhido para exemplo

In [59]:
# Exercicio escolhido
# Crie um DataFrame com as seguintes informações:
# Coluna "fruta": "Banana", "Maça", "Pera"
# Coluna "preço": 7.90, 10.20, 11.88
# Coluna "quantidade": 12, 3, 4

feira = np.array([["banana", "maca", "pera"],[7.90, 10.20, 11.88], [12, 3, 4]])

df = pd.DataFrame(feira.T, columns=["frutas", "preco", "quantidade"])

print(df)

   frutas  preco quantidade
0  banana    7.9         12
1    maca   10.2          3
2    pera  11.88          4


## 📌 0. Importação e Visualização dos Dados

Neste exemplo, trabalharemos com dados do ShoeFly.com, uma loja de calçados online fictícia. Podemos carregar dados no Pandas de um arquivo csv (variável separada por vírgula). Esses dados representam compras no ShoeFly.com. Vamos examinar as primeiras 10 linhas do nosso conjunto de dados:

In [12]:
import pandas as pd

df = pd.read_csv("shoefly_orders.csv")

In [113]:
df.head(10)

id first_name last_name                         email     shoe_type  \
0  54791    Rebecca   Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1  53450      Emily     Joyce        EmilyJoyce25@gmail.com  ballet flats   
2  91987      Joyce    Waller        Joyce.Waller@gmail.com       sandals   
3  14437     Justin  Erickson   Justin.Erickson@outlook.com         clogs   
4  79357     Andrew     Banks              AB4318@gmail.com         boots   
5  52386      Julie     Marsh        JulieMarsh59@gmail.com       sandals   
6  20487     Thomas    Jensen              TJ5470@gmail.com         clogs   
7  76971     Janice     Hicks        Janice.Hicks@gmail.com         clogs   
8  21586    Gabriel    Porter     GabrielPorter24@gmail.com         clogs   
9  62083    Frances    Palmer     FrancesPalmer50@gmail.com        wedges   

  shoe_material shoe_color  
0  faux-leather      black  
1  faux-leather       navy  
2        fabric      black  
3  faux-leather        red  
4       leather      brown  
5        fabric      black  
6        fabric       navy  
7  faux-leather       navy  
8       leather      brown  
9       leather      white

Note que o dataframe tem uma sequência de identificadores, os índices, mesmo tendo um outro identificador, o id, nesse exemplo.

Poderíamos setar o índice para ser justamente esse id, com o comando a seguir:

In [114]:
# Solução
df.set_index("id")

first_name   last_name                         email     shoe_type  \
id                                                                          
54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
53450       Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats   
91987       Joyce      Waller        Joyce.Waller@gmail.com       sandals   
14437      Justin    Erickson   Justin.Erickson@outlook.com         clogs   
79357      Andrew       Banks              AB4318@gmail.com         boots   
52386       Julie       Marsh        JulieMarsh59@gmail.com       sandals   
20487      Thomas      Jensen              TJ5470@gmail.com         clogs   
76971      Janice       Hicks        Janice.Hicks@gmail.com         clogs   
21586     Gabriel      Porter     GabrielPorter24@gmail.com         clogs   
62083     Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
91629     Jessica        Hale       JessicaHale25@gmail.com         clogs   
98602    Lawrence      Parker    LawrenceParker44@gmail.com        wedges   
45832       Susan      Dennis       SusanDennis58@gmail.com  ballet flats   
33862       Diane       Ochoa              DO2680@gmail.com       sandals   
73431     Rebecca     Charles     Rebecca.Charles@gmail.com         boots   
93889  Jacqueline       Crane            JC2072@hotmail.com        wedges   
39888     Vincent  Stephenson            VS4753@outlook.com         boots   
35961         Roy     Tillman        RoyTillman20@gmail.com         boots   
24560      Thomas    Roberson     Thomas.Roberson@gmail.com        wedges   
28559      Angela      Newton       ANewton1977@outlook.com        wedges   

      shoe_material shoe_color  
id                              
54791  faux-leather      black  
53450  faux-leather       navy  
91987        fabric      black  
14437  faux-leather        red  
79357       leather      brown  
52386        fabric      black  
20487        fabric       navy  
76971  faux-leather       navy  
21586       leather      brown  
62083       leather      white  
91629       leather        red  
98602        fabric      brown  
45832        fabric      white  
33862        fabric        red  
73431  faux-leather      white  
93889        fabric        red  
39888       leather      black  
35961       leather      white  
24560        fabric        red  
28559        fabric        red

Para retroceder e colocar o índice numérico como estava, basta:



In [115]:
# Solução

df.reset_index()

index     id  first_name   last_name                         email  \
0       0  54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com   
1       1  53450       Emily       Joyce        EmilyJoyce25@gmail.com   
2       2  91987       Joyce      Waller        Joyce.Waller@gmail.com   
3       3  14437      Justin    Erickson   Justin.Erickson@outlook.com   
4       4  79357      Andrew       Banks              AB4318@gmail.com   
5       5  52386       Julie       Marsh        JulieMarsh59@gmail.com   
6       6  20487      Thomas      Jensen              TJ5470@gmail.com   
7       7  76971      Janice       Hicks        Janice.Hicks@gmail.com   
8       8  21586     Gabriel      Porter     GabrielPorter24@gmail.com   
9       9  62083     Frances      Palmer     FrancesPalmer50@gmail.com   
10     10  91629     Jessica        Hale       JessicaHale25@gmail.com   
11     11  98602    Lawrence      Parker    LawrenceParker44@gmail.com   
12     12  45832       Susan      Dennis       SusanDennis58@gmail.com   
13     13  33862       Diane       Ochoa              DO2680@gmail.com   
14     14  73431     Rebecca     Charles     Rebecca.Charles@gmail.com   
15     15  93889  Jacqueline       Crane            JC2072@hotmail.com   
16     16  39888     Vincent  Stephenson            VS4753@outlook.com   
17     17  35961         Roy     Tillman        RoyTillman20@gmail.com   
18     18  24560      Thomas    Roberson     Thomas.Roberson@gmail.com   
19     19  28559      Angela      Newton       ANewton1977@outlook.com   

       shoe_type shoe_material shoe_color  
0          clogs  faux-leather      black  
1   ballet flats  faux-leather       navy  
2        sandals        fabric      black  
3          clogs  faux-leather        red  
4          boots       leather      brown  
5        sandals        fabric      black  
6          clogs        fabric       navy  
7          clogs  faux-leather       navy  
8          clogs       leather      brown  
9         wedges       leather      white  
10         clogs       leather        red  
11        wedges        fabric      brown  
12  ballet flats        fabric      white  
13       sandals        fabric        red  
14         boots  faux-leather      white  
15        wedges        fabric        red  
16         boots       leather      black  
17         boots       leather      white  
18        wedges        fabric        red  
19        wedges        fabric        red

Veja que surgiu uma coluna extra, caso não precise, você pode acrescentar a flag drop=True (use inplace=True se não quiser retornar para uma nova variável)

In [116]:
# Solução

df.reset_index(drop=True, inplace=True)
print(df)

       id  first_name   last_name                         email     shoe_type  \
0   54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1   53450       Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats   
2   91987       Joyce      Waller        Joyce.Waller@gmail.com       sandals   
3   14437      Justin    Erickson   Justin.Erickson@outlook.com         clogs   
4   79357      Andrew       Banks              AB4318@gmail.com         boots   
5   52386       Julie       Marsh        JulieMarsh59@gmail.com       sandals   
6   20487      Thomas      Jensen              TJ5470@gmail.com         clogs   
7   76971      Janice       Hicks        Janice.Hicks@gmail.com         clogs   
8   21586     Gabriel      Porter     GabrielPorter24@gmail.com         clogs   
9   62083     Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
10  91629     Jessica        Hale       JessicaHale25@gmail.com         clogs   
11  98602    Lawrence      P

In [117]:
# Solção

df.to_excel('shoefly_orders.xlsx', index=False)

Se você não sabe o nome das colunas para pesquisar, pode obter com o seguinte comando:



In [118]:
# Solção

df.columns
print(df)


       id  first_name   last_name                         email     shoe_type  \
0   54791     Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1   53450       Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats   
2   91987       Joyce      Waller        Joyce.Waller@gmail.com       sandals   
3   14437      Justin    Erickson   Justin.Erickson@outlook.com         clogs   
4   79357      Andrew       Banks              AB4318@gmail.com         boots   
5   52386       Julie       Marsh        JulieMarsh59@gmail.com       sandals   
6   20487      Thomas      Jensen              TJ5470@gmail.com         clogs   
7   76971      Janice       Hicks        Janice.Hicks@gmail.com         clogs   
8   21586     Gabriel      Porter     GabrielPorter24@gmail.com         clogs   
9   62083     Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
10  91629     Jessica        Hale       JessicaHale25@gmail.com         clogs   
11  98602    Lawrence      P

Para obter informações completas e detalhadas (para devs!), basta rodar o seguinte comando:



In [119]:
# Solução

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   id             20 non-null     int64 
 1   first_name     20 non-null     object
 2   last_name      20 non-null     object
 3   email          20 non-null     object
 4   shoe_type      20 non-null     object
 5   shoe_material  20 non-null     object
 6   shoe_color     20 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.2+ KB


## 📌 1. Extraindo as primeiras informações


Se você quiser apenas os e-mails de todos os clientes, basta selecionar pela coluna:



Ou quem pediu algum calçado branco ou preto?



In [ ]:
# Solução
emails = df.email
print(emails)

0     RebeccaLindsay57@hotmail.com
1           EmilyJoyce25@gmail.com
2           Joyce.Waller@gmail.com
3      Justin.Erickson@outlook.com
4                 AB4318@gmail.com
5           JulieMarsh59@gmail.com
6                 TJ5470@gmail.com
7           Janice.Hicks@gmail.com
8        GabrielPorter24@gmail.com
9        FrancesPalmer50@gmail.com
10         JessicaHale25@gmail.com
11      LawrenceParker44@gmail.com
12         SusanDennis58@gmail.com
13                DO2680@gmail.com
14       Rebecca.Charles@gmail.com
15              JC2072@hotmail.com
16              VS4753@outlook.com
17          RoyTillman20@gmail.com
18       Thomas.Roberson@gmail.com
19         ANewton1977@outlook.com
Name: email, dtype: object


Ou selecionar nome, sobrenome e email, o que faz mais sentido:



In [121]:
# Solução

lista = df[['first_name', 'last_name', 'email']]
print(lista)

    first_name   last_name                         email
0      Rebecca     Lindsay  RebeccaLindsay57@hotmail.com
1        Emily       Joyce        EmilyJoyce25@gmail.com
2        Joyce      Waller        Joyce.Waller@gmail.com
3       Justin    Erickson   Justin.Erickson@outlook.com
4       Andrew       Banks              AB4318@gmail.com
5        Julie       Marsh        JulieMarsh59@gmail.com
6       Thomas      Jensen              TJ5470@gmail.com
7       Janice       Hicks        Janice.Hicks@gmail.com
8      Gabriel      Porter     GabrielPorter24@gmail.com
9      Frances      Palmer     FrancesPalmer50@gmail.com
10     Jessica        Hale       JessicaHale25@gmail.com
11    Lawrence      Parker    LawrenceParker44@gmail.com
12       Susan      Dennis       SusanDennis58@gmail.com
13       Diane       Ochoa              DO2680@gmail.com
14     Rebecca     Charles     Rebecca.Charles@gmail.com
15  Jacqueline       Crane            JC2072@hotmail.com
16     Vincent  Stephenson     

Podemos selecionar todos que pediram sandálias pretas.



In [122]:
# Solução

df[(df.shoe_type == 'sandals') & (df.shoe_color == 'black')]

id first_name last_name                   email shoe_type shoe_material  \
2  91987      Joyce    Waller  Joyce.Waller@gmail.com   sandals        fabric   
5  52386      Julie     Marsh  JulieMarsh59@gmail.com   sandals        fabric   

  shoe_color  
2      black  
5      black

Ou quem pediu algum calçado branco ou preto?



In [ ]:
# Solução

#df[(df.shoe_color == 'white') | (df.shoe_color == 'black')]
df[df.shoe_color.isin(['white', 'black'])] 

id first_name   last_name                         email     shoe_type  \
0   54791    Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs   
2   91987      Joyce      Waller        Joyce.Waller@gmail.com       sandals   
5   52386      Julie       Marsh        JulieMarsh59@gmail.com       sandals   
9   62083    Frances      Palmer     FrancesPalmer50@gmail.com        wedges   
12  45832      Susan      Dennis       SusanDennis58@gmail.com  ballet flats   
14  73431    Rebecca     Charles     Rebecca.Charles@gmail.com         boots   
16  39888    Vincent  Stephenson            VS4753@outlook.com         boots   
17  35961        Roy     Tillman        RoyTillman20@gmail.com         boots   

   shoe_material shoe_color shoe_source  
0   faux-leather      black       vegan  
2         fabric      black       vegan  
5         fabric      black       vegan  
9        leather      white      animal  
12        fabric      white       vegan  
14  faux-leather      white       vegan  
16       leather      black      animal  
17       leather      white      animal

Vamos ver o que Susan Dennis pediu.



In [138]:
# Solução

df[(df.first_name == 'Susan') & (df.last_name == 'Dennis')]
 


id first_name last_name                    email     shoe_type  \
12  45832      Susan    Dennis  SusanDennis58@gmail.com  ballet flats   

   shoe_material shoe_color shoe_source  
12        fabric      white       vegan

Ainda é possível acessar diretamente usando loc ou iloc:



In [ ]:
# Soluções

df.loc[(df.shoe_type == 'sandals') & (df.shoe_color == 'black'), ['id', 'shoe_material' ]] # LOC - FAZ SELEÇÕES DE LINHAS E COLUNAS EM UM DATAFRAME


id shoe_material
2  91987        fabric
5  52386        fabric

In [ ]:
# Soluções

df.iloc[1,4] 
print(df.iloc[[0,2,5], 2])

0    Lindsay
2     Waller
5      Marsh
Name: last_name, dtype: object


Para criar novas colunas com valores baseados em condições usando função lambda, vamos ao seguinte exemplo: Muitos dos nossos clientes querem comprar sapatos veganos (sapatos feitos de materiais que não vêm de animais). Adicione uma nova coluna chamada shoe_source, que é vegan se os materiais não forem leather e animal caso contrário.

In [ ]:
# Soluções

df['shoe_source'] = df.shoe_material.apply(lambda x: 'vegan' if x != 'leather' else 'animal')
df.head()

id first_name last_name                         email     shoe_type  \
0  54791    Rebecca   Lindsay  RebeccaLindsay57@hotmail.com         clogs   
1  53450      Emily     Joyce        EmilyJoyce25@gmail.com  ballet flats   
2  91987      Joyce    Waller        Joyce.Waller@gmail.com       sandals   
3  14437     Justin  Erickson   Justin.Erickson@outlook.com         clogs   
4  79357     Andrew     Banks              AB4318@gmail.com         boots   

  shoe_material shoe_color shoe_source  
0  faux-leather      black       vegan  
1  faux-leather       navy       vegan  
2        fabric      black       vegan  
3  faux-leather        red       vegan  
4       leather      brown      animal

In [ ]:
# Carregar arquivo em CSV
df = pd.read_csv("Cancer_Data.csv") # df = pd.read_excel("arquivo.xlsx")
# Visualizar as 10 primeiras linhas
print(df.head(10))
# Visualizar as 5 últimas linhas
print(df.tail())
# Visualizar amostra aleatória de 5 linhas
print(df.sample(5))
# Verificar a estrutura da base de dados
print(df.info())
# Mostrar estatísticas descritivas das colunas numéricas
print(df.describe())
# Mostrar estatísticas de colunas categóricas
print(df.describe(include="object"))
# Verificar os tipos de dados de cada coluna
print(df.dtypes)
# Verificar o número de linhas e colunas
print(df.shape)
# Listar os nomes das colunas
print(df.columns)

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010 

## 📌 2. Tratamento de Valores Nulos

In [ ]:
# Verificar valores nulos

import pandas as pd
df = pd.read_csv("Cancer_Data.csv") # df = pd.read_xlxs("Cancer_Data.csv")
print(df.isnull().sum())

# Remover linhas com valores nulos
df = df.dropna()

# Remover colunas com muitos valores nulos
df = df.dropna(axis=1)

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [ ]:
# Preencher valores nulos com um valor específico
df.fillna({"coluna1": "valor_padrão", "coluna2": 0}, inplace=True)

# Preencher valores nulos com a média da coluna
df["coluna_numérica"] = df["coluna_numérica"].fillna(df["coluna_numérica"].mean())

# Preencher valores nulos com a mediana
df["coluna_numérica"] = df["coluna_numérica"].fillna(df["coluna_numérica"].median())

# Preencher valores nulos com a moda (valor mais frequente)
df["coluna_texto"] = df["coluna_texto"].fillna(df["coluna_texto"].mode()[0])

## 📌 3. Remoção de Duplicatas

In [ ]:
# Verificar duplicatas
print(df.duplicated().sum())

# Remover duplicatas (mantendo apenas a primeira ocorrência)
df = df.drop_duplicates()

# Remover duplicatas baseadas em uma ou mais colunas específicas
df = df.drop_duplicates(subset=["coluna1", "coluna2"])

## 📌 4. Manipulação de Tipos de Dados


In [ ]:
# Converter para número (se houver erro, substituir por NaN)
df["coluna_numérica"] = pd.to_numeric(df["coluna_numérica"], errors="coerce")

# Converter para string
df["coluna_texto"] = df["coluna_texto"].astype(str)

# Converter para categoria (melhora desempenho)
df["coluna_categorica"] = df["coluna_categorica"].astype("category")

# Converter para data
df["coluna_data"] = pd.to_datetime(df["coluna_data"], errors="coerce")

# Extrair ano, mês e dia de uma data
df["ano"] = df["coluna_data"].dt.year
df["mes"] = df["coluna_data"].dt.month
df["dia"] = df["coluna_data"].dt.day

## 📌 5. Manipulação de Strings

In [ ]:
# Remover espaços em branco extras
df["coluna_texto"] = df["coluna_texto"].str.strip()

# Converter para minúsculas
df["coluna_texto"] = df["coluna_texto"].str.lower()

# Converter para maiúsculas
df["coluna_texto"] = df["coluna_texto"].str.upper()

# Remover caracteres especiais
df["coluna_texto"] = df["coluna_texto"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

# Substituir palavras específicas
df["coluna_texto"] = df["coluna_texto"].str.replace("antiga", "nova")


## 📌 6. Filtragem de Dados

In [ ]:
# Filtrar valores maiores que 10
df_filtrado = df[df["coluna_numérica"] > 10]

# Filtrar valores dentro de um intervalo
df_filtrado = df[(df["coluna_numérica"] > 10) & (df["coluna_numérica"] < 50)]

# Filtrar registros que contêm uma palavra específica
df_filtrado = df[df["coluna_texto"].str.contains("palavra-chave", na=False)]

# Filtrar valores nulos
df_filtrado = df[df["coluna_texto"].isnull()]


## 📌 7. Alteração e Criação de Colunas



In [ ]:
# Criar uma nova coluna baseada em outra
df["nova_coluna"] = df["coluna_existente"] * 2

# Criar uma coluna com base em uma condição
df["categoria"] = df["coluna_numérica"].apply(lambda x: "Alto" if x > 100 else "Baixo")

# Criar uma coluna somando valores de outras colunas
df["total"] = df["coluna1"] + df["coluna2"]


## 📌 8. Ordenação de Dados

In [ ]:
# Ordenar por uma coluna
df = df.sort_values(by="coluna_numérica")

# Ordenar em ordem decrescente
df = df.sort_values(by="coluna_numérica", ascending=False)


## 📌 9. Renomeação de Colunas



In [ ]:
# Renomear uma coluna
df = df.rename(columns={"coluna_antiga": "coluna_nova"})

# Renomear várias colunas
df = df.rename(columns={"coluna1": "novo_nome1", "coluna2": "novo_nome2"})


## 📌 10. Reordenando Colunas

In [ ]:
# Alterar a ordem das colunas
df = df[["coluna2", "coluna1", "coluna3"]]


## 📌 11. Exportação dos Dados


In [ ]:
# Salvar em CSV
df.to_csv("dados_tratados.csv", index=False, encoding="utf-8")

# Salvar em Excel
df.to_excel("dados_tratados.xlsx", index=False)

# Salvar em JSON
df.to_json("dados_tratados.json", orient="records")


## 📌 12. Análise Estatística Básica


In [ ]:
# Contagem de valores únicos em uma coluna
print(df["coluna_categorica"].value_counts())

# Média de uma coluna numérica
print(df["coluna_numérica"].mean())

# Mediana
print(df["coluna_numérica"].median())

# Moda
print(df["coluna_numérica"].mode())

# Desvio padrão
print(df["coluna_numérica"].std())

# Correlação entre colunas numéricas
print(df.corr())
