## Aula de revisão + GITHUB



## Fluxos Sequeciais


Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o imposto de renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê: salário bruto. quanto pagou ao INSS. quanto pagou ao sindicato. o salário liquido. calcule os descontos e o salário líquido, conforme a tabela a baixo:

- Salário Bruto
- IR (11%)
- INSS(8%)
- SINDICATO (5%)

In [4]:
# Solução

# Pedir ao usuario o seu valor por hora

valor_hora = float(input("Digite o seu valor por hora: "))

# Pedir ao usuario o numero de horas trabalhadas no mês

horas_trabalhadas = float(input("Digite o numero de horas trabalhadas no mês: "))

# Multiplicar os dois valores anteriores e guardo numa variavel

salario_bruto = valor_hora * horas_trabalhadas

# Para saber o que pagar de IR, multiplico o salario bruto vezes 11% e guardo numa variavel

valor_ir = salario_bruto * 0.11

# Para saber o que pagar de INSS, multiplico o salario bruto vezes 8% guardo numa variavel

valor_inss = salario_bruto * 0.08

# Para saber o que pagar de SINDICATO, multiplico o salario bruto vezes 5% guardo numa variavel

valor_sindicato = salario_bruto * 0.05

# Imprimo a tabela conforme solicitado

print(f"- salário bruto: R${salario_bruto:.2f}")
print(f"- IR (11%): R${valor_ir:.2f}")
print(f"- INSS (8%): R${valor_inss:.2f}")
print(f"- Sindicato (5%): R${valor_sindicato:.2f}")
print(f"= Salário Liquido: R${salario_bruto - valor_ir - valor_inss - valor_sindicato:.2f}")


- salário bruto: R$2640.00
- IR (11%): R$290.40
- INSS (8%): R$211.20
- Sindicato (5%): R$132.00
= Salário Liquido: R$2006.40


## Fluxos Condicionais

Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:

"Telefonou para vitima?" "Esteve no local do crime ?" "Mora perto da vitima?" "Devia para a vitima?" "Já trabalhou com a vitima?"

O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".

In [20]:
# Solução

# Cria uma lista com todas as perguntas
perguntas = ["Telefonou para vitima?", "Esteve no local do crime?", "Mora perto da vitima?", "Devia para vitima?", "Ja trabalhou com vitima?"]

# Cria uma variável para armazenar as respostas

respostas = 0
# Orientar para que ele responda 0 (n) ou 1 (s)

print("Digite 0 para não e 1 para sim")

# Perguntar ao usuario seguindo a lista

for pergunta in range(len(perguntas)):

# A cada resposta, some a variável 0 (não) ou 1 (sim)

    respostas += int(input("pergunta"))


# Se a quantidade de resposta positivas for igual a 2, imprimir "suspeito"

if (respostas == 2):
    print("suspeito")

# Se a quantidade de resposta positivas for entre 3 e 4, imprimr "cumplice"

elif(respostas == 3 or 4):
    print("cumplice")

# Se a quantidade de resposta positivas for igual a 5, imprimir "assassino"

elif(respostas == 5):
    print("assasino")

# caso contrario, imprimir "inocente"

else:
    print("inocente")

Digite 0 para não e 1 para sim
suspeito


## Fluxos de Repetição

Crie um programa em Python que solicita ao usuario uma senha numérica de 4 digitos. O programa deve repetir essa solicitação até que o usuário informe a senha correta(1234)

In [1]:
# Solução

# Crie um programa em python que solicita ao usuario uma senha de 4 digitos

senha_digitada = int(input("Digite uma senha de 4 digitos: "))

# O programa deve repetir essa solicitação até que o usuario informe a senha correta 123

senha_correta = 1234

while senha_digitada != senha_correta:
    print("senha incorreta, tente novamente! ")
    senha_digitada = input("Digite a senha: ")

print("senha correta")
 

senha correta


# Uso de funções

In [ ]:
def saudacao_by_periodo(horario):
    
    if horario == "M" or "m": # SE 
        print("Bom dia! ")
    elif horario == "V" or "v": # ELSE + IF ---> DEFINE OUTRA CONDIÇÃO CASO A PRIMEIRA SEJA FALSA
        print("Boa tarde! ")
    elif horario == "N" or "n":
        print("Boa noite! ")
    else: # DEFINA UMA MENSAGEM SE TODAS AS CONDIÇÕES ANTERIORES FOREM FALSAS
        return "Valor inválido! "

horario = input("Digite o turno (M-matutino ou V-vespertino ou N-noturno): ")

turnos = ("M", "m", "V", "v", "N", "n")

while horario in turnos: # WHILE --> ENQUANTO A CONDIÇÃO FOR VERDADEIRA
    print(saudacao_by_periodo(horario))
    horario = input("Digite o turno (M-matutino ou V-vespertino ou N-noturno)")

Bom dia! 
None
Bom dia! 
None


## NUMPY: Exemplo

"Resenha de filme" é um site de resenhas de filmes onde quatro bons amiggos e criticos de filmes: gabriel, kleber, leandro e rodrigo assistem a filmes e dão a eles notas em uma escala de 0 a 100

In [ ]:
import numpy as np

[2.   0.75 2.   1.   0.5 ]


Quando toda turma classifica um filme, podemos armazenar suas classificações em um array NumPy movie_ratings:

In [8]:
movie_ratings = np.array([63.0, 54.0, 70.0, 50.0])
movie_ratings.dtype

random_ratings = np.random.rand(4,2)
random_ratings

array([[0.58019398, 0.40254031],
       [0.5708339 , 0.91162446],
       [0.51210616, 0.40730905],
       [0.23341728, 0.9870342 ]])

Mas eles assistem a mais de um filme, então temos que criar uma matriz bidimensional onde cada linha contém suas classificações para um filme específico.

In [18]:
movie_ratings = np.array([[63.0, 54.0, 70.0, 50.0],
                         [94.0, 85.0, 89.0, 95.0],
                         [64.0, 90.0, 73.0, 85.0]])
movie_ratings

array([[63., 54., 70., 50.],
       [94., 85., 89., 95.],
       [64., 90., 73., 85.]])

Alguns fãs preferem que os filmes sejam classificados em uma escala de cinco estrelas, então podemos usar o Numpy para dividir facilmente cada elemento por 20.

In [19]:
movie_ratings_stars = movie_ratings / 20
movie_ratings_stars

array([[3.15, 2.7 , 3.5 , 2.5 ],
       [4.7 , 4.25, 4.45, 4.75],
       [3.2 , 4.5 , 3.65, 4.25]])

Agora, digamos que as classificações estejam sempre na mesma ordem (Luísa, Maria, Tony, Kaio). Se quiséssemos criar uma matriz que tivesse apenas as classificações de Tony, poderíamos selecioná-las em nossa matriz movie_rastings.

In [26]:
tony_ratings = movie_ratings[:, 2]
tony_ratings

array([70., 89., 73.])

Agora, digamos que descobrimos que temos gostos muito parecidos com os de Maria, então queremos ver apenas filmes aos quais ele dá uma boa classificação. Podemos usar a lógica para selecionar esses filmes.

Vamos selecionar todas as classificações de Maria que são acima de 80:

In [28]:
maria_ratings = movie_ratings[:, 1]
maria_ratings[maria_ratings> 80]

array([85., 90.])

## Numpy: Exercicio

Farinha - 2 xícaras açúcar - 0,75 xícaras ovos - 2 ovos leite - 1 xícara manteiga - 0,5 xícaras 

Crie um array Numpy qeu represente esses dodos. Cada elemento deve ser um número (por exemplo, 2 para "2 xícaras"). Salve esse array como cupcakes.

In [29]:
# Solução
cupcakes = np.array([2, 0.75, 2, 1, 0.5])
print(cupcakes)

[2.   0.75 2.   1.   0.5 ]


A assistente de Joana compilou todas as suas receitas em um arquivo csv (comma-separated) chamado recipes.csv. Carregue esse arquivo em uma variável chamada recipes. Cada linha representa uma receita diferente. Cada coluna representa um ingrediente diferente.

In [50]:
# Solução
recipes = np.genfromtxt("recipes.csv", delimiter=",")
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

A 3 coluna representa o número de ovos que cada receita necessita

Selecione todos os elementos da 3 coluna e salve-os na variável eggs.

In [ ]:
# Solução

eggs = cupcakes[:2]
eggs

array([2.  , 0.75])

 Quais receitas exigem exatamente 1 ovo? Use uma declaração lógica para obter True ou False para cada valor de eggs.

In [33]:
# Solução

one_eggs = cupcakes[cupcakes == 1]
one_eggs

array([1.])

Joana fará 2 fornadas de cupcakes (1 fileira) a 1 fornadade biscoitos (3 fileira)

Você já tem uma variável para cupcakes. Crie uma variável cookies com os dados da 3 linha

In [51]:
# Solução

cookies = np.array(recipes[2]) # COPIA A LINHA 3 DO ARRAY RECIPES
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

Obtenha um número de ingredientes para uma porção dupla de cupcakes usando mulpiplicação em cupcakes.

Salve sua nova variavel em double_batch

In [34]:
# Solução
double_batch = cupcakes * 2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

Crie uma nova variável chamada grocery_list adicionando cookies e double_batch.

In [36]:
# Solução

#grocery_list = cookies + double_batch
grocery_list = np.array([cupcakes, double_batch])
grocery_list

array([[2.  , 0.75, 2.  , 1.  , 0.5 ],
       [4.  , 1.5 , 4.  , 2.  , 1.  ]])

## PANDAS: UMA BREVE INTRODUÇÃO

O pandas pode nos fornecer respostas sobre os dados, como por exemplo:

Existe uma correlação entre duas ou mais colunas? Qual é o valor? Qual o valor máximo? Qual o valor mínimo? O pandas também é capaz de excluir linhas que são irrelevantes ou que contêm valores incorretos, como valores vazios ou NULL, deixando os dados limpos.

Relacionando inicialmente as funções do Numpy com o pandas, poderíamos gerar uma série com os dados da porção dupla de cupcakes:

In [37]:
import pandas as pd

In [ ]:
double_batch_series = pd.Series(double_batch) # PARA INCLUIR INDICES PAR ACADA ELEMENTO
double_batch_series

0    4.0
1    1.5
2    4.0
3    2.0
4    1.0
dtype: float64

Podemos gerar um DataFrame a partir de várias series:

In [52]:
df = pd.DataFrame(recipes)
print(df)

      0      1    2    3      4
0  2.00  0.750  2.0  1.0  0.500
1  1.00  0.125  1.0  1.0  0.125
2  2.75  1.500  1.0  0.0  1.000
3  4.00  0.500  2.0  2.0  0.500


Por exemplo, se precisássemos listar as nossas compras do supermercado, teríamos algo semelhante a isso:

In [53]:
df = pd.DataFrame(recipes, columns=['Flour', 'Milk', 'Sugar', 'Butter', 'Eggs'])


In [54]:
df2 = pd.read_csv('recipes.csv', delimiter=',' , names=['Flour', 'Milk', 'Sugar', 'Butter', 'Eggs'])
print(df2)

   Flour   Milk  Sugar  Butter   Eggs
0   2.00  0.750      2       1  0.500
1   1.00  0.125      1       1  0.125
2   2.75  1.500      1       0  1.000
3   4.00  0.500      2       2  0.500


Exercicios escolhido para exemplo

In [49]:
# Exercicio escolhido
# Crie um DataFrame com as seguintes informações:
# Coluna "fruta": "Banana", "Maça", "Pera"
# Coluna "preço": 7.90, 10.20, 11.88
# Coluna "quantidade": 12, 3, 4

feira = np.array([["Banana", "Maça", "Pera"],[7.90, 10.20, 11.88], [12, 3, 4]])

df = pd.DataFrame(feira, columns=["Frutas", "preço", "quantidade"])

print(df)

   Frutas preço quantidade
0  Banana  Maça       Pera
1     7.9  10.2      11.88
2      12     3          4
